<div id="content" class="site-content">		
	<div id="primary" class="content-area"> 
		<div class="content">
			<section class="text_block">
				<div class="container">
					<div class="row">

						<h1 class="title">{t('SITE_TERMS_DEV_HEAD')}</h1>
						<small>{t('SITE_TERMS_DEV_SUBHEAD')}</small>

						<h2>Introduction</h2>
						<p>In order to use the PamFax API (the “PamFax API” or “API”), access the information contained on the PamFax website (the “Website”) or make use of the services provided by PamFax (the “Service” or “Services”), you (hereinafter referred to as “you”, “your” or “yourself”) must first read this agreement (the “Agreement”) and accept it. You may not avail yourself of the PamFax API, Website or Services if you do not accept this Agreement and the terms therein.</p>
						<p>By signing up or using the API or Services, you represent that you have read and agree to the terms and conditions of this Agreement, which also include and incorporate the <a href="{$action_terms}">Terms of Service (TOS)</a> and <a href="{$action_privacy}">Privacy Policy</a>. These terms and conditions will remain in effect throughout your use of the Services and continue after this Agreement expires, cancels or is terminated. These terms and conditions are legally binding should you choose to register for the Service. You may not use the API or Services and may not accept the terms if (a) you are not of legal age to form a binding contract with us, or (b) you are a person barred from receiving the Services under the laws of the Germany or other countries including the country in which you are a resident or from which you use the Services.</p>
						<p>The terms and conditions set forth herein may be amended in our sole and absolute discretion from time to time, and such amended terms and conditions shall be effective immediately upon posting to the Website. Your continued use of the Service after such posting will constitute acceptance by you of such amendments. It is your responsibility to review these Terms of Service frequently and remain informed about any changes to them, so we encourage you to visit this page often.</p>


						<h2>1. Grant of Rights to Use Services</h2>
						<p><b>1.1</b> Subject to your acceptance of and compliance with this Agreement and with the payment requirements for the Services, Scendix Vertriebsgesellschaft mbH (“Scendix”) hereby grants you a limited, non-exclusive, non-transferable, revocable, non-sublicenseable right and license, in and under our intellectual property rights, to access and use the Services, solely in accordance with the terms and conditions of this Agreement. Unless explicitly stated otherwise, any new features provided by PamFax that augment or enhance the current Services shall also constitute “Services” and shall be subject to these terms and conditions. You may not, nor allow any third party to, copy, distribute, sell, disclose, lend, transfer, convey, modify, decompile, disassemble or reverse engineer the Services for any purpose whatsoever. You may not allow any unauthorized third party to access the Services for any purpose whatsoever. All rights not expressly granted under this Agreement are retained by Scendix.</p>
						<p><b>1.2</b> You may write a software application or Website (an “Application”) that interfaces with the Services. You acknowledge that we may change, deprecate or republish APIs for any Service or feature of a Service from time to time, and that it is your responsibility to ensure that calls or requests you make to or via our Service are compatible with then-current APIs for the Service. Scendix will attempt to inform you of any changes with reasonable notice so you can adjust your Application, but we are under no obligation to do so.</p>
						<p><b>1.3</b> You and any Applications that you may build, distribute, or otherwise create may make network calls or requests to the Services, or may send/receive faxes via the Service, at any time that the Services are available provided that those requests do not violate the terms of Section 10 or other terms of this Agreement.</p>
						<p><b>1.4</b> You may not remove, obscure, or alter any notice of any Scendix trademark, service mark or other intellectual property or proprietary right appearing on the Website or contained within the Services.</p>
						<p><b>1.5</b> Provided that you comply with the terms of this Agreement and our policies and procedures including Section 10, you may use the Services to execute Applications owned or lawfully obtained by you. You are solely responsible for your Applications, including any data, text, images or content contained therein.</p>
						<p><b>1.6</b> You are personally responsible for all traffic originating from your Applications using your account credentials to the Services. As such, you should protect your authentication keys and security credentials. Actions taken using your credentials shall be deemed to be actions taken by you, with all consequences including service termination, civil and criminal penalties.</p>
						<p><b>1.7</b> We may make available to you, for your installation, copying and/or use in connection with the Services, from time to time, a variety of software, data and other content and printed and electronic documentation (the “PamFax Properties”). Subject to your acceptance of this Agreement, ongoing compliance with its terms and conditions with respect to the subject Service, and payment if and as required for your right to use the subject Service, we hereby grant to you, without the right to sublicense, a limited, non-exclusive, non-transferable license during the Term of this Agreement (as defined in Section 2.1), under our intellectual property or proprietary rights in the PamFax Properties, only to install, copy and use the PamFax Properties solely in connection with and as necessary for your use of such Services and solely to the extent in compliance with all the terms and conditions of this Agreement.</p>

						<p>
							<b>(a)</b> The PamFax Properties may include, without limitation:
							<ul class="simple-ul">
								<li>The PamFax Website;</li>
								<li>PamFax APIs and PamFax Markup Language;</li>
								<li>Specifications describing the operational and functional capabilities, use limitations, technical and engineering requirements, and testing and performance criteria relevant to the proper use of a Service and its related APIs and technology;</li>
							</ul>
						</p>

						<p>
							<b>(b)</b> Scendix may make available under another license agreement, such as an open source agreement, additional content or software. Any such content or software will be clearly marked with such a license indicating the usage rights available for that content or software. For such content or software released pursuant to an open license, Scendix encourages you to modify, alter, tamper with, repair and/or create derivative works consistent with such license. Such content or software may include:
							<ul class="simple-ul">
								<li>Developer tools, such as software development kits or sample code, for use in connection with the APIs;</li>
								<li>Articles and documentation for use in connection with the use and implementation of the APIs (collectively, “Documentation”);</li>
							</ul>
						</p>

						<p>
							<b>(c)</b> Except as may be expressly authorized under this Agreement:
							<ul class="simple-ul">
								<li>You may not, and may not attempt to, modify, alter, tamper with, repair, or otherwise create derivative works of any software included in the PamFax Properties.</li>
								<li>You may not, and may not attempt to, reverse engineer, disassemble, or decompile the PamFax Properties or the Services or apply any other process or procedure to derive the source code of any software included in the PamFax Properties.</li>
							</ul>
						</p>

						<p><b>1.8</b> For purposes of this Agreement, Scendix hereby grants to you a non-transferable, non-sublicenseable, non-exclusive license during the Term of this Agreement to display the trade names, trademarks, service marks, logos, domain names of PamFax (each, a “Scendix Mark”) for the purpose of promoting or advertising that you use the Service. In return you hereby grant Scendix a non-transferable, non-sublicenseable, non-exclusive license during the Term of this Agreement to display your trade names, trademarks, service marks, logos, domain names and the like for the purpose of promoting or advertising that you use the Service. In using Scendix Marks, you may not: (i) display a Scendix Mark in any manner that implies a relationship or affiliation with, sponsorship, or endorsement by Scendix; (ii) use Scendix’s Marks to disparage Scendix or its products or services; or (iii) display a Scendix Mark on a site that violates any law or regulation. Notwithstanding the above, Scendix may determine in its sole discretion whether its marks may be used in connection with your Application. Furthermore, we may modify any Scendix Marks provided to you at any time, and upon notice, you will use only the modified Scendix Marks and not the old Scendix Marks. Other than as specified in this Agreement, you may not use any Scendix Mark unless you obtain our prior written consent.</p>
						<p><b>1.9</b> The rights granted by us in this Agreement with respect to the PamFax Properties, the Scendix Marks and the Services are nonexclusive, and we reserve the right to: (i) act as a developer of products or services related to any of the products that you may develop in connection with the PamFax Properties or via your use of the Services; and (ii) appoint third parties as developers or systems integrators who may offer products or services which compete with your Application.</p>
						<p><b>1.10</b> Without limitation to Section 6, we shall have no liability whatsoever for any damage, liabilities, losses (including any loss of data or profits) or any other consequences that you may incur with respect to loss of data associated with your account and data therein.</p>

						<h2>2. Term, Termination and Suspension</h2>

						<p><b>2.1</b> The term (“Term”) of this Agreement will commence once you accept this Agreement as provided above. The Agreement will remain in effect until terminated by you or us in accordance with this Section 2.</p>
						<p><b>2.2</b> You may terminate this Agreement for any reason or no reason at all, at your convenience, by deleting your PamFax account.</p>
						<p><b>2.3</b> We may suspend your right and license to use any or all Services or terminate this Agreement in its entirety (and, accordingly, cease providing all Services to you), for any reason or for no reason, at our discretion at any time by providing you up to thirty (30) days’ advance notice in accordance with the notice provisions set forth in Section 9 below.</p>
						<p><b>2.4</b> We may suspend your right and license to use the Service or terminate this Agreement in its entirety (and, accordingly, your right to use the Service), for cause effective as set forth below:</p>
						<p><b>2.4.1</b> Immediately upon our notice to you in accordance with the notice provisions set forth in Section 9 below if (i) you violate any provision of Section 10 or we have reason to believe that you have violated Section 10, (ii) there is an unusual spike or increase in your use of the Services for which there is reason to believe such traffic or use is fraudulent or negatively impacting the operating capability of the Service; (iii) we determine, in our sole discretion, that our provision of any of the Services to you is prohibited by applicable law, or has become impractical or unfeasible for any legal or regulatory reason; or (iv) subject to applicable law, upon your liquidation, commencement of dissolution proceedings, disposal of your assets, failure to continue your business, assignment for the benefit of creditors, or if you become the subject of a voluntary or involuntary bankruptcy or similar proceeding.</p>
						<p><b>2.4.2</b> Immediately and without notice if you are in default of any payment obligation with respect to any of the Services or if any payment mechanism you have provided to us is invalid or charges are refused for such payment mechanism.</p>
						<p><b>2.4.3</b> Five (5) days following our provision of notice to you in accordance with the notice provisions set forth in Section 9 below if you breach any other provision of this Agreement and fail, as determined by us, in our sole discretion, to cure such breach within such 5-day period.</p>
						<p><b>2.5</b> Effect of Suspension or Termination.</p>
						<p><b>2.5.1</b> Upon our suspension of your use of any Services, in whole or in part, for any reason: (i) fees will continue to accrue for any Services that are still in use by you, notwithstanding the suspension; (ii) you remain liable for all fees, charges and any other obligations you have incurred through the date of suspension with respect to the Services; and (iii) all of your rights with respect to the Services shall be terminated during the period of the suspension.</p>
						<p><b>2.5.2</b> Upon termination of this Agreement for any reason: (i) you remain liable for all fees, charges and any other obligations you have incurred through the date of termination with respect to the Services; and (ii) all of your rights under this Agreement shall immediately terminate.</p>
						<p><b>2.6</b> In the event this Agreement is terminated for any reason, Sections 5, 6, 7 and 8 will survive any such termination.</p>
						<p><b>2.7</b> Following the suspension or termination of your right to use the Services by us or by you for any reason other than a termination for cause, you shall be entitled to take advantage of any post-termination assistance we may generally elect to make available with respect to the Services such as data retrieval arrangements. We may also endeavor to provide you with unique post-suspension or post-termination assistance, but we shall be under no obligation to do so. Your right to take advantage of any such assistance, whether generally made available with respect to the Services or made available uniquely to you, shall be conditioned upon your acceptance of and compliance with any fees and terms we specify for such assistance.</p>

						
						<h2>3. Downtime and Service Suspensions; Security</h2>
						<p><b>3.1</b> The Services are provided on a best-efforts basis. In addition to our rights to terminate or suspend Services to you as described in Section 2 above, you acknowledge that: (i) your access to and use of the Services may be suspended for the duration of any unanticipated or unscheduled downtime or unavailability of any portion or all of the Services for any reason, including as a result of power outages, system failures or other interruptions; and (ii) we shall also be entitled, without any liability to you, to suspend access to any portion or all of the Services at any time, on a Service-wide basis: (a) for scheduled downtime to permit us to conduct maintenance or make modifications to any Service; (b) in the event of a denial of service attack or other attack on the Service or other event that we determine, in our sole discretion, may create a risk to the applicable Service, to you or to any of our other customers if the Service were not suspended; or (c) in the event that we determine that any Service is prohibited by law or we otherwise determine that it is necessary or prudent to do so for legal or regulatory reasons (collectively, “Service Suspensions”). Without limitation to Section 6, we shall have no liability whatsoever for any damage, liabilities, losses (including any loss of data or profits) or any other consequences that you may incur as a result of any Service Suspension. To the extent we are able, we will endeavor to provide you notice of any Service Suspension in accordance with the notice provisions set forth in Section 9 below and to post updates regarding resumption of Services following any such suspension, but shall have no liability for the manner in which we may do so or if we fail to do so.</p>
						<p><b>3.2</b> We strive to keep information you provide to us secure, but cannot guarantee that we will be successful at doing so. Accordingly, without limitation to Section 6 below, you acknowledge that you bear sole responsibility for adequate security, protection and backup of your content including all data associated with your account. We strongly encourage you, where available and appropriate, to use encryption technology to protect your content from unauthorized access and to routinely archive your content. We will have no liability to you for any unauthorized access or use, corruption, deletion, destruction or loss of any of your content.</p>

						<h2>4. Fees</h2>
						<p><b>4.1</b> You may create PamFax user accounts via the PamFax API. These are limited to 50 free user accounts per API account. Once you have reached the limit a charge will be required to add additional user accounts to your API.</p>
						<p><b>4.2</b> All fees payable by you are exclusive of applicable taxes and duties, including, without limitation, VAT and applicable sales tax. You will provide such information to us as reasonably required to determine whether we are obligated to collect any taxes from you.</p>
						<p><b>4.3</b> We may specify the manner in which you will pay any fees, and any such payment shall be subject to our general accounts receivable policies from time to time in effect. All amounts payable by you under this Agreement will be made without setoff or counterclaim and without deduction or withholding. If any deduction or withholding is required by applicable law, you shall notify us and shall pay such additional amounts to us as necessary to ensure that the net amount that we receive, after such deduction and withholding, equals the amount we would have received if no such deduction or withholding had been required. Additionally, you shall provide us with documentation that the withholding and deducted amounts have been paid to the relevant taxing authority.</p>
						<p><b>4.4</b> Should you have any dispute as to fees associated with your account, please contact us at support@pamfax.biz within 30 days of the date of the activity that generated such dispute, and we will attempt to resolve the matter. Any and all refunds issued to resolve such a dispute shall be issued as credits to your account, but in no event shall there be any cash refunds. Disputes older than 30 days shall not be entitled to any refunds or credits.</p>

						<h2>5. Intellectual Property</h2>
						<p><b>5.1</b> Other than the limited use and access rights and licenses expressly set forth in this Agreement, we reserve all right, title and interest (including all intellectual property and proprietary rights) in and to: (i) the Services; (ii) the PamFax Properties; (iii) the Scendix Marks; and (iv) any other technology and software that we provide or use to provide the Services and the PamFax Properties. You do not, by virtue of this Agreement or otherwise, acquire any ownership interest or rights in the Services, the PamFax Properties, the Scendix Marks, or such other technology and software, except for the limited use and access rights described in this Agreement.</p>
						<p><b>5.2</b> Scendix may, at its discretion, offer certain Software Development Kits, tools, application samples, or documentation under an open source license. Any such products will be marked with copyright details, and those copyrights will apply to those and only those documents. Scendix reserves all rights to any documents, tools, services, technologies and the like not designated with an open license.</p>
						<p><b>5.3</b> Other than the rights and interests expressly set forth in this Agreement and excluding any and all works derived from PamFax Properties, you reserve all right, title and interest (including all intellectual property and proprietary rights) in and to: (i) content and data you may send to us or use as part of your use of any Services (“your Content”); and (ii) your Applications.</p>
						<p><b>5.4</b> In the event you elect, in connection with any of the Services, to communicate to us suggestions for improvements to the Services, the PamFax Properties or the Scendix Marks (collectively, “Feedback”), we shall own all right, title, and interest in and to the same, even if you have designated the Feedback as confidential, and we shall be entitled to use the Feedback without restriction. Furthermore, any other content or information you post or provide to Scendix via comments, forums, emails and the like (collectively, “Communications”) shall be considered the property of Scendix. You hereby irrevocably assign all right, title and interest in and to the Feedback and Communications to us and agree to provide us such assistance as we may require to document, perfect and maintain our rights to the Feedback and Communications.</p>
						<p><b>5.5</b> During and after the Term of the Agreement, with respect to any of the Services that you elect to use, you will not assert, nor will you authorize, assist, or encourage any third party to assert, against us or any of our customers, end users, vendors, business partners (including third party sellers on websites operated by or on behalf of us), sublicensees or transferees, any patent infringement or other intellectual property infringement claim with respect to such Services.</p>

						<h2>6. Representations and Warranties; Disclaimers; Limitations of Liability</h2>
						<p><b>6.1</b> You represent and warrant that you will not use the Website (including our forums and comments sections), Services, PamFax Properties, Scendix Marks, your Application or your Content in a manner that violates Section 10. To this effect, we ask that you take reasonable precautions to promote best practices. Although Scendix does not assume the duty or obligation to monitor any materials created, posted or uploaded by you or any third parties, Scendix reserves the right, in its sole and absolute discretion, to monitor any and all materials posted or uploaded by you or any third parties at any time without prior notice to ensure that they conform to any usage guidelines or policies relating to our Website or Services.</p>
						<p><b>6.2</b> You represent and warrant: (i) that you are solely responsible for the development, operation, and maintenance of your Application and for your Content, including without limitation, the accuracy, appropriateness and completeness of your Content and all product-related materials and descriptions; (ii) that you have the necessary rights and licenses, consents, permissions, waivers and releases to use and display your Application and your Content; (iii) that neither your Application nor your Content (a) violates, misappropriates or infringes any rights of us or any third party, (b) constitutes defamation, invasion of privacy or publicity, or otherwise violates any rights of any third party, or (c) is designed for use in any illegal activity or promotes illegal activities, including, without limitation, in a manner that might be libelous or defamatory or otherwise malicious, illegal or harmful to any person or entity, or discriminatory based on race, sex, religion, nationality, disability, sexual orientation, or age; (iv) that neither your Application nor your Content contains any harmful components; and (v) to the extent to which you use any of the Scendix Marks, that you will conduct your business in a professional manner and in a way that reflects favorably on the goodwill and reputation of Scendix and its products. You also represent and warrant that you are responsible for any charges incurred by virtue of your use of the Application, no matter whether the Application acted in error.</p>
						<p><b>6.3</b> You represent and warrant that you have read and understood the Privacy Policy and General Terms of Service, and you agree to abide by their terms, where applicable, including as incorporated by reference herein. You further agree to abide by all applicable local, state, national, foreign and international laws and regulations and that you will be solely responsible for all acts or omissions that occur under your account or password, including the content of your transmissions through the Service.</p>
						<p><b>6.4</b> You represent and warrant that without Scendix’s express written consent you will not use, and will not authorize any third party to use, any Public Software (as defined below) in connection with the Services in any manner that requires, pursuant to the license applicable to such Public Software, that any PamFax Properties or Services be (a) disclosed or distributed in source code form, (b) made available free of charge to recipients, or (c) modifiable without restriction by recipients. With respect to any Feedback or Communications, you represent and warrant that such Feedback and Communications, in whole or in part, contributed by or through you, (i) is legally distributable by you, either because you own the copyright or because you have fully complied with any copyright terms associated with the software or content, (ii) contains no third party software or any software that may be considered Public Software and (iii) does not violate, misappropriate or infringe any intellectual property rights of any third party. “Public Software” means any software, documentation or other material that contains, or is derived (in whole or in part) from, any software, documentation or other material that is distributed as free software, open source software (e.g., Linux) or similar licensing or distribution models, including, but not limited to software, documentation or other material licensed or distributed under any of the following licenses or distribution models, or licenses or distribution models similar to any of the following: (i) GNU’s General Public License (GPL), Lesser/Library GPL (LGPL), or Free Documentation License, (ii) The Artistic License (e.g., PERL), (iii) the Mozilla Public License, (iv) the Netscape Public License, (v) the Sun Community Source License (SCSL), (vi) the Sun Industry Standards License (SISL), (vii) the BSD License and (viii) the Apache License.</p>
						<p><b>6.5</b> You represent and warrant that: (i) the information you provide in connection with your registration for the Services is accurate and complete; (ii) you are duly authorized to do business in the jurisdiction where you operate; and (iii) you are an authorized representative of your entity duly authorized to access the Services and to legally bind you to this Agreement and all transactions conducted under your account.</p>
						<p><b>6.6</b> PAMFAX PROPERTIES, THE SCENDIX MARKS, THE SERVICES AND ALL TECHNOLOGY, SOFTWARE, FUNCTIONS, CONTENT, IMAGES, MATERIALS AND OTHER DATA OR INFORMATION PROVIDED BY US OR OUR LICENSORS IN CONNECTION THEREWITH (COLLECTIVELY THE “SERVICE OFFERINGS”) ARE PROVIDED “AS IS.” WE AND OUR LICENSORS MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE WITH RESPECT TO THE SERVICE OFFERINGS. EXCEPT TO THE EXTENT PROHIBITED BY APPLICABLE LAW, WE AND OUR LICENSORS DISCLAIM ALL WARRANTIES, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, QUIET ENJOYMENT, AND ANY WARRANTIES ARISING OUT OF ANY COURSE OF DEALING OR USAGE OF TRADE. WE AND OUR LICENSORS DO NOT WARRANT THAT THE SERVICE OFFERINGS WILL FUNCTION AS DESCRIBED, WILL BE UNINTERRUPTED OR ERROR FREE, OR FREE OF HARMFUL COMPONENTS, OR THAT THE DATA YOU STORE WITHIN THE SERVICE OFFERINGS WILL BE SECURE OR NOT OTHERWISE LOST OR DAMAGED. WE AND OUR LICENSORS SHALL NOT BE RESPONSIBLE FOR ANY SERVICE INTERRUPTIONS, INCLUDING, WITHOUT LIMITATION, POWER OUTAGES, SYSTEM FAILURES OR OTHER INTERRUPTIONS. NO ADVICE OR INFORMATION OBTAINED BY YOU FROM US OR FROM ANY THIRD PARTY OR THROUGH THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS AGREEMENT.</p>
						<p><b>6.7</b> In addition to the foregoing, we specifically disclaim all liability, and you shall be solely responsible for the development, operation, and maintenance of your Application and for all materials that appear on or within your Application and you agree that you shall, without limitation, be solely responsible for:</p>
						<p><b>6.8.1</b> the technical operation of your Application and all related equipment;</p>
						<p><b>6.8.2</b> the accuracy and appropriateness of any materials posted on or within your Application (including, among other things, any product-related materials);</p>
						<p><b>6.8.3</b> ensuring that any materials posted on your site or within your Application do not violate Section 10, are not illegal and do not promote illegal activities, including without limitation any activities that might be libelous or defamatory or otherwise malicious, illegal or harmful to any person or entity, or discriminatory based on race, sex, religion, nationality, disability, sexual orientation, or age;</p>
						<p><b>6.8.4</b> ensuring that your Application accurately and adequately discloses, either through a privacy policy or otherwise, how you collect, use, store, and disclose data collected from visitors, including, where applicable, that third parties (including advertisers) may serve content and/or advertisements and collect information directly from visitors and may place or recognize cookies on visitors’ browsers; and</p>
						<p><b>6.8.5</b> any of your users’ or customers’ claims relating to your Application or any Services utilized in connection with your Application.</p>
						<p><b>6.9</b> NEITHER WE NOR ANY OF OUR LICENSORS SHALL BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER LOSSES (EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES) IN CONNECTION WITH THIS AGREEMENT, INCLUDING, WITHOUT LIMITATION, ANY SUCH DAMAGES RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICES; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES; OR (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR CONTENT. IN ANY CASE, OUR AGGREGATE LIABILITY UNDER THIS AGREEMENT SHALL BE LIMITED TO THE AMOUNT ACTUALLY PAID BY YOU TO US HEREUNDER FOR THE SERVICES DURING THE PRECEDING TWELVE (12) MONTHS. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OR ALL OF THE ABOVE EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</p>
					
						<h2>7. Indemnification</h2>
						<p><b>7.1</b> you agree to indemnify, defend and hold us, our affiliates and licensors, each of our and their business partners (including third party sellers on websites operated by or on behalf of us) and each of our and their respective employees, officers, directors and representatives, harmless from and against any and all claims, losses, damages, liabilities, judgments, penalties, fines, costs and expenses (including reasonable attorneys fees), arising out of or in connection with any claim arising out of (i) your use of the Services, PamFax Properties and/or Scendix Marks in a manner not authorized by this Agreement, and/or in violation of the applicable restrictions, and/or applicable law, (ii) your Application, your Content, or the combination of either with other applications, content or processes, including but not limited to any claim involving infringement or misappropriation of third-party rights and/or the use, development, design, manufacture, production, advertising, promotion and/or marketing of your Application and/or your Content, (iii) your violation of any term or condition of this Agreement or any applicable additional policies, including without limitation, your representations and warranties, or (iv) you or your employees’ or personnel’s negligence or willful misconduct.</p>
						<p><b>7.2</b> We agree to promptly notify you of any claim subject to indemnification; provided that our failure to promptly notify you shall not affect your obligations hereunder except to the extent that our failure to promptly notify you delays or prejudices your ability to defend the claim. At our option, you will have the right to defend against any such claim with counsel of your own choosing (subject to our written consent) and to settle such claim as you deem appropriate, provided that you shall not enter into any settlement without our prior written consent and provided that we may, at any time, elect to take over control of the defense and settlement of the claim.</p>


						<h2>8. Disputes</h2>
						<p><b>8.1</b> Notwithstanding anything to the contrary, we may seek injunctive or other relief in any state, federal, or national court of competent jurisdiction for any actual or alleged infringement of Scendix’s or any third party’s intellectual property and/or proprietary rights. Any dispute hereunder shall be adjudicated in any state or federal court in Hamburg, Germany, and you consent to exclusive jurisdiction and venue in such courts. You further acknowledge that our rights in the PamFax Properties and the Scendix Marks are of a special, unique, extraordinary character, giving them peculiar value, the loss of which cannot be readily estimated and may not be adequately compensated for in monetary damages.</p>
						<p><b>8.2</b> By using the Services, you agree that the laws of Germany, without regard to principles of conflicts of laws, will govern this Agreement and any dispute of any sort that might arise between you and us.</p>


						<h2>9. Notices</h2>
						<p><b>9.1</b> Notices made by us under this Agreement for you or your account specifically (e.g., notices of breach and/or suspension) will be provided to you via a notification message displayed on your account page or via the email address provided to us in your registration for the Services or in any updated email address you provide to us in accordance with standard account information update procedures we may provide from time to time. It is your responsibility to keep your email address current and you will be deemed to have received any email sent to any such email address, upon our sending of the email, whether or not you actually receive the email.</p>
						<p><b>9.2</b> For notices made by you to us under this Agreement and for questions regarding this Agreement or the Services, you may contact Scendix as follows: by postal mail at Scendix Vertriebsgesellschaft mbH, Am Hornsgehege 6-8, 29574 Ebstorf, Germany, or by contacting us at support@pamfax.biz.</p>
						
						<h2>10. Acceptable use</h2>

						<p>
							<b>10.1</b> Defines acceptable use and actions that Scendix prohibits. This list is provided by way of example and shall not be considered exhaustive. Any use not covered here is not to be assumed to be acceptable.
							<ul class="simple-ul">
								<li>You may not deploy applications or services that contain endless loops.</li>
								<li>Any application or session should contain an explicit termination event.</li>
								<li>No application will be launched on the Scendix production network until the pre-paid funds have been received and credited to your account.</li>
								<li>Actions that restrict or inhibit any person, whether a customer of Scendix or otherwise, in its use of products and services that leverage Scendix resources is prohibited.</li>
								<li>You may not reverse engineering of any product or service provided by Scendix.</li>
								<li>Exploitation of known bugs or limitations in any of the services deployed on your behalf to circumvent billing or impact the system in a way that violates any other requirements listed in the acceptable use policy (see TOS) is prohibited.</li>
								<li>Use of undocumented features and methods is strictly at your own risk. Any claims, support issues or acceptable use policy violations resulting from such use will be at your expense.</li>
								<li>Executing any program or process that will intercept data not intended for your application or service is prohibited.</li>
								<li>Introduction of malicious programs into the network or systems (e.g., viruses and worms) is prohibited.</li>
								<li>Effecting security breaches or disruptions of the Services is prohibited. Security breaches include, but are not limited to, accessing data of which you are not an intended recipient or accessing a server or account that you are not expressly authorized to access. For purposes of this bullet point, “disruption” includes, but is not limited to, war dialing, flood pings, packet spoofing, and forged telephony information.</li>
								<li>Circumventing user authentication or security of any host, network or account is prohibited.</li>
								<li>Interfering with or denying service to any user, system or service is prohibited.</li>
								<li>Using any program/script/command, or sending messages of any kind, designed to interfere with a user’s session, service or application is prohibited.</li>
								<li>Furnishing false or incorrect data on the Scendix required documentation including account setup or other applicable agreements and Scendix documents is prohibited.</li>
								<li>Attempting to circumvent or alter the processes or systems that measure time, bandwidth utilization, or other methods for calculating your use of Scendix’s products and services is prohibited.</li>
								<li>You may not send unsolicited messages, including mass faxing, or the distribution through Scendix’s systems of other advertising material to individuals who did not specifically request such material.</li>
								<li>Any activities that violate anti-spamming laws and regulations such as the CAN SPAM Act of 2003 is prohibited.</li>
								<li>Harassment, whether through language, frequency or size of messages is prohibited.</li>
								<li>Unauthorized use, or forging, of identity information is prohibited.</li>
								<li>Using Scendix or your account to collect replies to messages sent from another provider, which violate the AUP rules or those of that provider is prohibited.</li>
								<li>You may not use any of the Scendix Properties other than as expressly permitted in the Terms of Service.</li>
								<li>Transmitting any material that may infringe the intellectual property rights or other rights of third parties, including but not limited to trademark, copyright or rights of publicity or otherwise violating, infringing, or misappropriating the rights of any third party.</li>
								<li>Promoting or engaging in illegal activities.</li>
								<li>Engaging in activities or transmitting through the Services any information that may be libelous or defamatory or otherwise malicious or harmful to any person or entity, or discriminatory based on race, sex, religion, nationality, disability, sexual orientation, or age.</li>
								<li>Violating or facilitating the violation of any German, European Union or foreign law regarding the transmission of technical data or software.</li>
								<li>Interfering with or disrupting networks connected to the Services or violating the regulations, policies or procedures of such networks.</li>
							</ul>
							Violation may result in the immediate suspension or termination of your account, civil and/or criminal liability, and Scendix may, in addition to any remedy that it may have at law or in equity, terminate permission for you to use the Services. In such event, you are still liable for any and all outstanding charges accumulated through your use of the Services, including uses in violation of acceptable use or the laws of any jurisdiction. In addition, Scendix may investigate incidents that are contrary to the acceptable use and provide requested information to third parties who have provided notice to Scendix stating that they have been harmed by your failure to abide by the acceptable use. Scendix’s failure to enforce this policy in each and every instance in which it might have application does not amount to a waiver of Scendix’s rights hereunder.						
						</p>

						<p>
							<b>10.1</b> Restrictions on Use. You agree to ensure that the Services will not be used in or for any illegal, fraudulent, unauthorized or improper manner or purpose and will only be used in compliance with all applicable laws, rules and regulations, including all applicable state, federal, and international Internet, data, telecommunications, telemarketing, “spam,” and import/export laws and regulations, including the U.S. Export Administration Regulations. 
							Without limiting the foregoing, you agree not to permit the Services to be used to transmit or disseminate any:
							<ul class="simple-ul">
								<li>junk fax, spam, or unsolicited material to persons or entities that have not agreed to receive such material or to whom you or your end-users do not otherwise have a legal right to send such material;</li>
								<li>material that infringes or violates any third party’s intellectual property rights, rights of publicity, privacy, or confidentiality;</li>
								<li>material or data, that is illegal, or material or data, as determined by Scendix (in Scendix’s sole discretion), that is harassing, coercive, defamatory, libelous, abusive, threatening, obscene, or otherwise objectionable, materials that are harmful to minors or excessive in quantity, or materials the transmission of which could diminish or harm the reputation of Scendix or any third-party service provider involved in the provision of the Services;</li>
								<li>viruses, Trojan horses, worms, time bombs, or other computer programming routines that are intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data, or personal information;</li>
								<li>material or information that is false, misleading, or inaccurate;</li>
								<li>material that would expose Scendix, any third-party service provider involved in providing the Services, or any other third party to liability; and/or</li>
								<li>any signal or impulse that could cause electrical, magnetic, optical, or other technical harm to the equipment or facilities of Scendix or any third party.</li>
							</ul>
						</p>

						<p><b>10.3</b> You shall not access any Services that you have not ordered or for which you have not paid the applicable fees. You will not use or attempt to use a third party’s account with Scendix, or interfere with the security of, or otherwise abuse, the Services or other Scendix customers. You shall not interfere in any manner with Scendix’s provision of the Services.</p>

						<h2>11. Miscellaneous Provisions</h2>

						<p><b>11.1</b> Responsibility. If you authorize, assist, encourage or facilitate another person or entity to take any action related to the subject matter of this Agreement, you shall be deemed to have taken the action yourself.</p>
						<p><b>11.2</b> Severability. If any portion of this Agreement is held by a court of competent jurisdiction to be invalid or unenforceable, the remaining portions of this Agreement will remain in full force and effect, and any invalid or unenforceable portions shall be construed in a manner that most closely reflects the effect and intent of the original language. If such construction is not possible, the provision will be severed from this Agreement, and the rest of the Agreement shall remain in full force and effect.</p>
						<p><b>11.3</b> Waivers. The failure by us to enforce any provision of this Agreement shall in no way be construed to be a present or future waiver of such provision nor in any way affect our right to enforce such provision thereafter. All waivers by us must be in writing to be effective.</p>
						<p><b>11.4</b> Successors and Assigns. This Agreement will be binding upon, and inure to the benefit of the parties and their respective successors and assigns.</p>
						<p><b>11.5</b> Entire Agreement. This Agreement incorporates by reference all policies and guidelines posted on the PamFax Website and as may be modified thereafter (including the General Terms of Service and the Privacy Policy) and constitutes the entire agreement between you and us regarding the subject matter hereof and supersedes any and all prior or contemporaneous representation, understanding, agreement, or communication between you and us, whether written or oral, regarding such subject matter.</p>
						<p><b>11.6</b> No Endorsement. You understand and acknowledge that we are not certifying nor endorsing, and have no obligation to certify or endorse, any of your Applications or your Content.</p>
					</div>
				</div>
			</section>												
		</div>
	</div>
</div> <!-- #content -->