<div id="content" class="site-content">		
	<div id="primary" class="content-area"> 
		<div class="content">
			<section class="text_block">
				<div class="container">
					<div class="row">

						<h1 class="title">{t('SITE_TERMS_HEAD')}</h1>
						<small>{t('SITE_TERMS_SUBHEAD')}</small>
						
						{if $curr_lang != 'en'}<p>{t(SITE_TERMS_ENGLISH_NOTE, ['[a]' => '<a href="'|cat:$action_privacy|cat:'">'])}</p>{/if}						

						<h2>Introduction</h2>
						<p>Welcome to PamFax, owned and operated by PamConsult Software-Beratungsgesellschaft mbH, Unterschlei?heim, Germany (“the Site”). Please read the following Terms of Use carefully before using this Site or ordering/downloading any of our products, so that you are aware of your legal rights and obligations with respect to PamConsult and its affiliates and subsidiaries (individually and collectively, “PamConsult”). By using the Site, purchasing software or other products, you signify your irrevocable acceptance of these Terms of Use. You also agree to ensure that anyone who uses this software on your computer also abides by the Terms of Use. PamConsult has the right to revise the Terms of Use at any time without providing notice to its users. Your continued use of the site and/or service shall be deemed irrevocable acceptance of those revisions. We reserve the right to change, modify, suspend or discontinue any portion of the Site and/or service at any time. We may also impose limits on certain features or restrict your access to parts or the entire site and/or service without notice or liability. Please also take time to read our Privacy Policy, which is a legal component of the Term of Use.</p>
			
						<h2>Use of PamFax Software and Service</h2>
						<p>PamFax services, sometimes referred to as the “Software” and accompanying documentation that are made available by download from this Site are the copyrighted work of PamConsult. Use of the Software is governed by the terms of the end user license agreement that accompanies or is included with such Software.</p>
						
						<h2>Warranties and Disclaimers</h2>
						<p>Except as expressly provided otherwise in a written agreement between you and PamConsult, the materials in or purchased through this site and/or client application are provided “as is” and without warranties of any kind either express or implied. To the fullest extent permissible pursuant to applicable law, PamConsult disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability or fitness for a particular purpose, or the warranty of non-infringement. Without limiting the foregoing, PamConsult does not warrant that the functions contained in the service or software will be uninterrupted or error-free, that defects will be corrected, or that this service or the server that makes it available are free of viruses or other harmful components. PamConsult does not warrant or make any representations regarding the use or the results of the use of the materials in this service in terms of their correctness, accuracy, reliability, or otherwise. Applicable law may not allow the exclusion of implied warranties, so the above exclusion may not apply to you. Without limitation of the foregoing, you acknowledge that as a service to users of the PamConsult service and software, we include links to other web sites on the world wide web portion of the internet and that PamConsult has no control over, and makes no representations of any kind whatsoever, regarding the content or appropriateness of content on such web sites and you hereby irrevocably waive any claim against us with respect to such web sites. Under no circumstances, including, but not limited to, negligence, shall PamConsult be liable for any special or consequential damages that result from the use of, or the inability to use, the materials, the site, client application or any other web site, even if PamConsult or a PamConsult authorized representative has been advised of the possibility of such damages. Applicable law may not allow the limitation or exclusion of liability for incidental or consequential damages, so the above limitation or exclusion may not apply to you. No advice or information, whether written or oral, obtained by you from PamConsult or from or through the site shall create any warranty not expressly stated in the terms of use. In no event shall PamConsult’s total liability to you for all damages, losses, and causes of action (whether in contract, tort (including, but not limited to, negligence) or otherwise) exceed the amount paid by you, if any, for purchasing any services, materials or products.</p>

						<h2>Term of Use</h2>
						<p>The license for use of the Site and the Materials is effective until terminated. You may terminate it at any time by destroying the Materials together with all copies thereof. This license will terminate upon conditions set forth elsewhere within this Terms of Use or if you fail to comply with any term or condition of this Terms of Use. In such event, no notice shall be required by PamConsult to effect such termination. Upon termination of this Terms of Use, you agree to destroy the Materials together with all backup copies, modifications, printed or written materials, and merged portions in any form, or return same to PamConsult at your expense.</p>

						<h2>Update</h2>
						<p>PamConsult reserves the right to modify these Terms of Service at any time by publishing the revised Terms of Service on the Website, which shall become effective within thirty (30) days from the date of publication, unless You expressly accept the revised Terms of Service earlier by clicking on the accept button. Your continued use of the Products after expiry of the 30-day period shall constitute your acceptance to be bound by the terms and conditions of the revised version of the Terms of Service. If You do not wish to accept these revised Terms of Service, You are entitled to terminate Your User Account by contacting our customer support team, with effect from the date on which the revised Terms of Service would become effective.</p>

						<h2>Web Site Links</h2>
						<p>PamConsult may provide links to other sites that we feel are relevant and interesting to our users (“Link Sites”). PamConsult is not responsible for the content on the Link Sites and is not responsible for the accuracy of the information and intellectual property notices therein. Some of these Link Sites may provide you with opportunities to purchase products (“Products”). We do not endorse any of the Products nor do we make any representations or warranties in connection with the Products.</p>

						<h2>Online Behaviour</h2>
						<p>Please exercise respect when participating in any of PamConsult’s community features such as Forums, Bulletin Boards, Chat Rooms, etc. (“User Materials”). you may not submit or publish through PamConsult any User Materials that are libelous, defamatory, pornographic, an invasion of privacy, obscene, abusive, illegal, racist, offensive, an infringement on any intellectual property rights of a third party or would otherwise violate the rights of any third party. Furthermore, you may not submit or publish User Materials through PamConsult that solicit funds or services, contain advertising or include programs that contain viruses or any other programs designed to impair the functionality of any computer. Please remember that we do not regularly monitor the contents of these community features and cannot be held responsible for the User Materials. Therefore, we apologize in advance for any offensive or otherwise displeasing User Materials. If at any time you upload or post User Materials, including but not limited to comments, suggestions, problem reports, bug reports, translations and design ideas to the Site you automatically grant PamConsult a non-exclusive, royalty-free, perpetual license of all rights throughout the universe to use, edit, modify, include, incorporate, adapt, record and reproduce the User Materials including, without limitation, all trademarks associated therewith, in any manner whatsoever, in or out-of-context, in all languages, in all media now known and hereafter devised, and to use the User Materials in advertising, promotion and publicity for the Site, PamConsult and its or their products and services, in any and all media now known or hereafter devised. In addition, you represent and warrant that you are entitled to enter into these Terms of Use and that you waive any so-called “moral rights” in and to the User Materials.</p>

						<h2>Submissions</h2>
						<p>Certain parts of the Site may ask for written suggestions or problem reports such as using our contact form or problem report form (“Submissions”). The Submissions shall be deemed the property of PamConsult. PamConsult shall exclusively own all now known or hereafter existing rights to the Submissions throughout the universe in perpetuity and shall be entitled to use the Submissions for any purpose whatsoever, commercial or otherwise, without compensation to the provider of the Submissions. In any event, any Submissions you send to PamConsult will not be treated as confidential and PamConsult shall not be liable for any disclosure of the Submissions.</p>

						<h2>Datenschutz (Applies to users in Germany)</h2>
						<p>Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. („Google“). Google Analytics verwendet sog. „Cookies“, Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermoglichen. Die durch den Cookie erzeugten Informationen uber Ihre Benutzung dieser Website werden in der Regel an einen Server von Google in den USA ubertragen und dort gespeichert. Im Falle der Aktivierung der IP-Anonymisierung auf dieser Webseite, wird Ihre IP-Adresse von Google jedoch innerhalb von Mitgliedstaaten der Europaischen Union oder in anderen Vertragsstaaten des Abkommens uber den Europaischen Wirtschaftsraum zuvor gekurzt. Nur in Ausnahmefallen wird die volle IP-Adresse an einen Server von Google in den USA ubertragen und dort gekurzt. Im Auftrag des Betreibers dieser Website wird Google diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports uber die Websiteaktivitaten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenuber dem Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser ubermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengefuhrt. Sie konnen die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht samtliche Funktionen dieser Website vollumfanglich werden nutzen konnen. Sie konnen daruber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verfugbare Browser-Plugin herunterladen und installieren (http://tools.google.com/dlpage/gaoptout?hl=de).</p>

						<h2>Administrative Information Jurisdictional Issues</h2>
						<p>This Site is controlled and operated by PamConsult Software-Beratungsgesellschaft mbH. PamConsult makes no representation that materials in the Site are appropriate or available for use in your location. Those who choose to access this Site from any location do so on their own initiative and are responsible for compliance with local laws, if and to the extent local laws are applicable. We explicitly are not responsible for content on websites that we link to and these links are provided for informational purposes and are to be used at your own risk. We do not carry any responsibility for content posted by registered or non-registered users on the forum or any social platforms like but not limited to Twitter, Facebook, etc.</p>

						<h2>Indemnity</h2>
						<p>You agree to indemnify and hold PamConsult, and its subsidiaries, affiliates, officers, agents, co-branders or other partners, and employees, harmless from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of content you submit, post to or transmit through the Site, your use of the Site, your connection to the Site, your violation of the Terms of Use, or your violation of any rights of another person or entity.</p>

						<h2>Governing Law</h2>
						<p>By accessing this Site, you and PamConsult agree that all matters relating to your access to, or use of, this Site shall be governed by and construed in accordance with the laws of Germany, without giving effect to any principles of conflicts of law. Neither the UN-treaty (CISG) nor any other existing or future bilateral or international treaties, even if implemented into German law, shall be applicable.</p>

						<h2>Trademarks</h2>
						<p>The trademarks, logos and service marks (“Marks”) displayed on this Site are the property of PamConsult or other third parties. You are not permitted to use the Marks without the prior written consent of PamConsult or such third party, which may own the Marks. PamConsult, the PamConsult logo are trademarks of PamConsult.</p>

						<h2>Fax Privacy</h2>
						<p>PamConsult acknowledges that documents contain proprietary and confidential information. PamConsult agrees to keep the documents in confidence and to take reasonable precautions to ensure that data is stored securely, no unauthorized individuals have access to the documents and that no unauthorized copies are made. For privacy reasons sent faxes are deleted automatically after one month from your fax history, except the history of Pro Plan subscribers where the history is retained. It is your responsibility to download copies, should you need them. Communication between the PamFax application and our servers is completely SSL encrypted.</p>

						<h2>Payment</h2>
						<p>You shall pay PamConsult, via respective payment processing company (Gate2Shop, Paypal or other available payment companies), any applicable rates as stated on the website in connection with your purchase of respective products or services.</p>

						<h2>Refunds</h2>
						<p>When you purchase Paid-For-Products directly from PamConsult you will be entitled to a cancellation period of fifteen (15) days (a “Cooling-Off Period”) unless you have made use of the Paid-For-Products in any way, in which case the Cooling-Off Period will be extinguished and your purchase cannot be cancelled or refunded. Outside of the Cooling-Off Period, only subscriptions are refundable unless used or expired. Expenditure of PamFax Credit, allocation of a Fax Number, or use of any aspect of a subscription amounts to “use” of a Paid-For-Product. You hereby expressly agree that Fax Numbers may be allocated before the end of the Cooling-Off Period. The Cooling-Off Period and refunds do not apply to Paid-For-Products that are (i) purchased via a third party partner of PamConsult (please contact the partner directly, who may decide in its sole discretion whether or not to pay a refund), (ii) not directly acquired online from PamConsult (e.g. vouchers or pre-paid cards) and (iii) paid for and allocated to your PamConsult Account by a PamFax Company Manager administrator. If you believe that PamConsult has charged you in error, you must contact PamConsult within 90 days of such charge. No refunds will be given for any charges which are more than 90 days old. PamConsult reserves the right to refuse a refund request if it reasonably believes (i) that you are trying to unfairly exploit this refund policy, for example, by making repetitive refund requests in respect of the same Product; (ii) if you are in breach of these Terms or (iii) if PamConsult reasonably suspects that you are using our Products or Software fraudulently or that your User Account is being used by a third party fraudulently. This refund policy does not affect your statutory rights.</p>

						<h2>Rates</h2>
						<p>Our rates apply to fax pages that take less than 60 seconds to transmit, which covers approximately 90% of all fax pages. Faxes, regardless of size, to numbers that take longer than 60 seconds per page to transmit will be added to a “slow fax number list”. Next time you send to the same number a surcharge will be added to the price based on the last transmission speed. Should the fax be sent within the 60 seconds per page limit, a refund for the surcharge is issued after completion of the fax job. No special offers apply. German 19% Value Added Tax (VAT) may apply to all charges depending on your country of residence.</p>

						<h2>Change of rates</h2>
						<p>PamConsult may change the rates at any time by giving a thirty (30) day notice of such change on the website www.pamfax.biz, or by stating new rates in connection with your purchase. The new rate will apply to your next purchase after the adjustments have been published on the website. You agree that by continuing to use PamFax following the adjustments of the rates, you accept the new rates. If you do not wish to accept such adjustment of rates, you may ask for a refund of your PamFax Credit (only not reactivated PamFax Credit is refundable).</p>

						<h2>Payment and tariff Issues</h2>
						<p>PamFax Credit: You need to pay to use certain products. To purchase payable products you need a sufficient balance of PamFax credit, which is credit purchased by you (or an Administrator of the PamFax Company Manager account) from PamConsult and allocated to your User Account (“PamFax Credit”). You must deposit sufficient PamFax Credit in your User Account through your debit or credit card, PayPal, promotional voucher, or other means which may be made available by PamConsult. PamConsult reserves the right to stop accepting debit or credit cards from one or more issuers. – Restrictions: PamConsult does not guarantee that you will be able to use your PamFax Credit balance to purchase all the payable products. Certain products may have to be paid for separately. Inactive PamFax Credit: If You do not use your PamFax Credit for a period of 180 days, we will place your PamFax Credit on inactive status. You can reactivate the PamFax Credit by signing into your account and opening the PamFax Portal. There is no charge for reactivation. PamConsult does not reactivate PamFax Credit for you. Reactivated PamFax Credit is not refundable. Sign up PamFax Credit bonus: PamConsult may provide you with a sign up bonus. This is a non-refundable monetary amount automatically added to your PamFax account after account creation. Bonus credit is provided at the sole discretion of PamConsult and may be changed or removed.</p>

						<h2>Fair use of Service</h2>
						<p>In case where PamConsult finds or suspects unfair use of the Site and/or service, we reserve the right to change, modify, suspend or discontinue user access to any portion of the Site and/or service at any time. We may impose limits on certain features or restrict your access to parts or the entire site and/or service without notice or liability. PamFax does not charge for failed faxes – independent of cause – except when free credit was used for payment (applies currently to the initial sign up credit and referral credit). When the system encounters other errors or errors related to the PamFax system, either the fax will be resent again at no charge or the total payment amount will be refunded automatically (except when paying with free credit). The fair use policy applies to failed fax sending – as soon as a certain level of failed fax delivery is reached all future failed faxes in the job will be charged for pro-rata. Only failures where a communication cost has occurred will be charged for.</p>

						<h2>Additional terms for the use of Fax Number</h2>
						<p>1. Allocation of your Fax Number. If you have bought and are eligible for a Fax Number, it will be allocated to you as soon as reasonably possible after you have paid us. In certain countries, the number may be allocated to you by PamConsult’s partner instead of PamConsult and you may need to enter into a separate agreement with such partner. You acknowledge and understand that the allocation and distribution of the number does not constitute any transfer of any property or other rights with respect to the Fax Number(s).</p>
						<p>2. PamFax Company Manager. If a Fax Number is allocated to you by the administrator, the right to use the Fax Number and the cancellation of such right will be exercised by the administrator at his sole discretion. PamConsult shall try to allocate and distribute the requested number and enable you to be reached by PSTN fax machines on your number, where applicable. However, PamConsult cannot guarantee that the requested Fax Number(s) can be allocated or distributed to you or that you can make use of the PamConsult services using such number.</p>
						<p>3. Termination of Fax Numbers. PamConsult is entitled to refuse, change or terminate any Fax Number allocated to you at any time for any reason, including but not limited to: (i) if you don’t comply with these Terms of Service or any of the applicable Additional Terms; (ii) if you don’t comply with any instructions given by PamConsult and/or its partners in relation to the products in accordance with paragraph 5 below; and/or (iii) if the Fax Number is withdrawn, terminated or changed by any of PamConsult’s partners for any reason.</p>
						<p>4. In the event that PamConsult changes the Fax Number that has been allocated to you, PamConsult will send a notification by e-mail and/or chat message, stating the effective date of the change and your new Fax Number. If you do not wish to accept this new Fax Number, you are entitled to terminate your Fax Number, in writing or by e-mail to sales@pamhelp.com, with effect from the date on which the new number will be allocated to you.</p>
						<p>5. Your co-operation – You agree that you will: (i) comply with any reasonable instructions given by PamConsult or PamConsult’s partners with regard to the use of the Fax Number(s) and the products including but not limited to compliance with any terms of service of PamConsult’s partners; (ii) provide accurate and complete information with regard to your place of residence and your use of the Fax Number(s), and such other information as may reasonably be required from time to time by PamConsult.</p>

						<p><br /><br /><strong>© 2006-2015 PamConsult Software-Beratungsgesellschaft mbH Last revised: December 16, 2014</strong></p>

					</div>
				</div>
			</section>												
		</div>
	</div>
</div> <!-- #content -->